const $=s=>document.querySelector(s);let S={grid:3,qs:[],img:null,time:300,left:300,i:0,done:0,right:0,open:new Set,locked:new Set,timer:null,end:false};
document.querySelectorAll("#gridChoices button").forEach(b=>b.onclick=()=>{S.grid=+b.dataset.grid;document.querySelectorAll("#gridChoices button").forEach(x=>x.classList.toggle("active",x===b));check()});document.querySelector("#gridChoices button").classList.add("active");
$("#imageInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{S.img=r.result;$("#preview").innerHTML="<img src='"+r.result+"'>";check()};r.readAsDataURL(f)};
$("#excelInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let wb=XLSX.read(await f.arrayBuffer(),{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});S.qs=rows.map(r=>{let n={};Object.keys(r).forEach(k=>n[k.trim().toLowerCase()]=r[k]);let g=(...a)=>{for(let k of a)if(n[k]!=null&&n[k]!=="")return String(n[k]).trim();return""};return{q:g("câu hỏi","cau hoi","question"),A:g("a","đáp án a"),B:g("b","đáp án b"),C:g("c","đáp án c"),D:g("d","đáp án d"),ans:g("đáp án","dap an","answer").toUpperCase().charAt(0)}}).filter(x=>x.q&&x.A&&x.B&&x.C&&x.D&&"ABCD".includes(x.ans));check()}catch(e){$("#validation").textContent="Không đọc được file Excel/CSV."}};
function check(){let n=S.grid*S.grid,ok=S.img&&S.qs.length>=n;$("#validation").textContent=ok?"✓ Sẵn sàng: "+n+" mảnh / "+n+" câu":"Cần ảnh và ít nhất "+n+" câu hỏi hợp lệ.";$("#validation").className=ok?"validation ok":"validation err";$("#startBtn").disabled=!ok}
$("#time").onchange=e=>S.time=+e.target.value;$("#startBtn").onclick=start;$("#finishBtn").onclick=finish;$("#newGameBtn").onclick=reset;$("#resetBtn").onclick=reset;
function start(){S.left=S.time;S.done=0;S.right=0;S.open=new Set;S.locked=new Set;S.end=false;S.qs=S.qs.slice(0,S.grid*S.grid);if($("#order").value==="shuffle")S.qs.sort(()=>Math.random()-.5);$("#setup").classList.add("hidden");$("#result").classList.add("hidden");$("#game").classList.remove("hidden");$("#meta").textContent=S.grid+"×"+S.grid+" • "+S.qs.length+" câu";let b=$("#board");b.style.gridTemplateColumns="repeat("+S.grid+",1fr)";b.innerHTML="";for(let i=0;i<S.qs.length;i++){let d=document.createElement("div");d.className="tile";d.innerHTML="<span class='num'>"+(i+1)+"</span><img>";b.appendChild(d)}next();clearInterval(S.timer);S.timer=setInterval(tick,1000)}
function next(){if(S.done>=S.qs.length)return finish();S.i=S.done;let q=S.qs[S.i];$("#qindex").textContent="Câu "+(S.i+1)+" / "+S.qs.length;$("#question").textContent=q.q;$("#feedback").textContent="";$("#answers").innerHTML="";["A","B","C","D"].forEach(k=>{let b=document.createElement("button");b.className="answer";b.innerHTML="<b>"+k+".</b><span>"+q[k]+"</span>";b.onclick=()=>answer(k);$("#answers").appendChild(b)})}
function answer(k){let q=S.qs[S.i];document.querySelectorAll(".answer").forEach(b=>b.disabled=true);S.done++;if(k===q.ans){S.right++;S.open.add(S.i);let t=document.querySelectorAll(".tile")[S.i];t.classList.add("open");t.querySelector("img").src=S.img;$("#feedback").textContent="✓ Chính xác! Mảnh ghép đã mở."}else{S.locked.add(S.i);document.querySelectorAll(".tile")[S.i].classList.add("locked");$("#feedback").textContent="✕ Sai. Mảnh ghép không được mở; câu này đã khóa."}$("#score").textContent=S.right*100+" điểm";$("#progressText").textContent=S.done+"/"+S.qs.length+" câu • Mở "+S.open.size+" mảnh";$("#bar").style.width=(S.done/S.qs.length*100)+"%";setTimeout(next,600)}
function tick(){S.left--;let m=Math.floor(S.left/60),s=S.left%60;$("#timer").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0");if(S.left<=0)finish()}
function finish(){if(S.end)return;S.end=true;clearInterval(S.timer);$("#game").classList.add("hidden");$("#result").classList.remove("hidden");$("#summary").innerHTML="Đúng <b>"+S.right+"/"+S.qs.length+"</b> câu · mở được <b>"+S.open.size+"</b> mảnh.";let r=$("#resultBoard");r.style.gridTemplateColumns="repeat("+S.grid+",1fr)";r.innerHTML="";for(let i=0;i<S.qs.length;i++){let d=document.createElement("div");d.className="tile "+(S.open.has(i)?"open":"locked");d.innerHTML="<span class='num'>"+(i+1)+"</span><img src='"+(S.open.has(i)?S.img:"")+"'>";r.appendChild(d)}}
function reset(){clearInterval(S.timer);location.reload()}check();