const $=s=>document.querySelector(s);
let S={grid:3,qs:[],img:null,time:300,left:300,i:0,done:0,right:0,open:new Set,locked:new Set,timer:null,end:false,student:false,name:"",answerMode:"hide",payload:null};

document.querySelectorAll("#gridChoices button").forEach(b=>b.onclick=()=>{S.grid=+b.dataset.grid;document.querySelectorAll("#gridChoices button").forEach(x=>x.classList.toggle("active",x===b));check()});
document.querySelector("#gridChoices button").classList.add("active");

$("#imageInput").onchange=e=>{let f=e.target.files[0];if(!f)return;$("#imageName").textContent=f.name;let r=new FileReader();r.onload=()=>{S.img=r.result;$("#preview").innerHTML="<img src='"+r.result+"' alt='Ảnh xem trước'>";check()};r.readAsDataURL(f)};
$("#excelInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;$("#excelName").textContent=f.name;try{let wb=XLSX.read(await f.arrayBuffer(),{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});S.qs=rows.map(r=>{let n={};Object.keys(r).forEach(k=>n[k.trim().toLowerCase()]=r[k]);let g=(...a)=>{for(let k of a)if(n[k]!=null&&n[k]!=="")return String(n[k]).trim();return""};return{q:g("câu hỏi","cau hoi","question"),A:g("a","đáp án a"),B:g("b","đáp án b"),C:g("c","đáp án c"),D:g("d","đáp án d"),ans:g("đáp án","dap an","answer").toUpperCase().charAt(0)}}).filter(x=>x.q&&x.A&&x.B&&x.C&&x.D&&"ABCD".includes(x.ans));check()}catch(e){$("#validation").textContent="Không đọc được file Excel/CSV.";$("#validation").className="validation err"}};

function check(){let n=S.grid*S.grid,ok=!!S.img&&S.qs.length>=n;$("#validation").textContent=ok?"✓ Sẵn sàng: "+n+" mảnh / "+n+" câu":"Cần ảnh và ít nhất "+n+" câu hỏi hợp lệ.";$("#validation").className=ok?"validation ok":"validation err";$("#startBtn").disabled=!ok;$("#shareBtn").disabled=!ok}
$("#time").onchange=e=>S.time=+e.target.value;$("#answerMode").onchange=e=>S.answerMode=e.target.value;$("#startBtn").onclick=()=>start(false);$("#shareBtn").onclick=createShare;$("#copyShareBtn").onclick=copyShare;$("#studentStart").onclick=()=>{S.student=true;S.name=$("#studentName").value.trim()||"Học sinh";start(true)};$("#finishBtn").onclick=finish;$("#newGameBtn").onclick=()=>location.href=location.pathname;$("#resetBtn").onclick=()=>location.href=location.pathname;

function prepare(){S.left=S.time;S.done=0;S.right=0;S.open=new Set;S.locked=new Set;S.end=false;S.i=0;S.qs=S.qs.slice(0,S.grid*S.grid);if($("#order").value==="shuffle"&&!S.student)S.qs.sort(()=>Math.random()-.5)}
function start(student=false){S.student=student;prepare();$("#setup").classList.add("hidden");$("#student").classList.add("hidden");$("#result").classList.add("hidden");$("#game").classList.remove("hidden");$("#gameMeta").textContent=S.grid+"×"+S.grid+" • "+S.qs.length+" câu"+(S.student?" • "+S.name:"");let b=$("#board");b.style.gridTemplateColumns="repeat("+S.grid+",1fr)";b.innerHTML="";for(let i=0;i<S.qs.length;i++){let d=document.createElement("div");d.className="tile";d.innerHTML="<span class='num'>"+(i+1)+"</span><img>";b.appendChild(d)}updateUI();next();clearInterval(S.timer);S.timer=setInterval(tick,1000)}

function next(){if(S.done>=S.qs.length)return finish();S.i=S.done;let q=S.qs[S.i];$("#qIndex").textContent="Câu "+(S.i+1)+" / "+S.qs.length;$("#qStatus").textContent="Chưa trả lời";$("#question").textContent=q.q;$("#feedback").textContent="";$("#feedback").className="feedback";$("#answers").innerHTML="";["A","B","C","D"].forEach(k=>{let b=document.createElement("button");b.className="answer";b.innerHTML="<b>"+k+".</b><span>"+q[k]+"</span>";b.onclick=()=>answer(k);$("#answers").appendChild(b)})}

function answer(k){if(S.end)return;let q=S.qs[S.i];document.querySelectorAll(".answer").forEach(b=>b.disabled=true);S.done++;let ok=k===q.ans;$("#qStatus").textContent=ok?"Đúng":"Sai";if(ok){S.right++;S.open.add(S.i);let t=document.querySelectorAll(".tile")[S.i];t.classList.add("open");t.querySelector("img").src=S.img;$("#feedback").textContent="✓ Chính xác! Mảnh ghép đã mở." ;$("#feedback").className="feedback ok"}else{S.locked.add(S.i);document.querySelectorAll(".tile")[S.i].classList.add("locked");$("#feedback").textContent="✕ Sai. Mảnh ghép không được mở; câu này đã khóa.";$("#feedback").className="feedback bad";if(S.answerMode==="show")$("#feedback").textContent+=" Đáp án: "+q.ans}updateUI();setTimeout(next,650)}

function updateUI(){$("#score").textContent=(S.right*100)+" điểm";$("#progressText").textContent=S.done+"/"+S.qs.length+" câu • Mở "+S.open.size+" mảnh";$("#progressBar").style.width=(S.done/S.qs.length*100)+"%"}

function tick(){S.left--;let m=Math.floor(Math.max(0,S.left)/60),s=Math.max(0,S.left)%60;$("#timer").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0");if(S.left<=0)finish()}

function finish(){if(S.end)return;S.end=true;clearInterval(S.timer);$("#game").classList.add("hidden");$("#result").classList.remove("hidden");$("#resultSummary").innerHTML=(S.student?"<b>"+S.name+"</b> — ":"")+"Đúng <b>"+S.right+"/"+S.qs.length+"</b> câu · mở được <b>"+S.open.size+"</b> mảnh · <b>"+(S.right*100)+" điểm</b>.";let r=$("#resultBoard");r.style.gridTemplateColumns="repeat("+S.grid+",1fr)";r.innerHTML="";for(let i=0;i<S.qs.length;i++){let d=document.createElement("div");d.className="tile "+(S.open.has(i)?"open":"locked");d.innerHTML="<span class='num'>"+(i+1)+"</span><img src='"+(S.open.has(i)?S.img:"")+"'>";r.appendChild(d)}}

function toBase64(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj))))}
function fromBase64(s){return JSON.parse(decodeURIComponent(escape(atob(s))))}

function resizeImage(dataUrl){return new Promise(resolve=>{let im=new Image();im.onload=()=>{let c=document.createElement("canvas"),w=960,h=540;c.width=w;c.height=h;let ctx=c.getContext("2d");ctx.drawImage(im,0,0,w,h);resolve(c.toDataURL("image/jpeg",.62))};im.src=dataUrl})}
async function createShare(){if(!S.img||S.qs.length<S.grid*S.grid)return;$("#shareBtn").disabled=true;$("#shareBtn").textContent="⏳ Đang tạo link...";try{let img=await resizeImage(S.img),data={v:1,title:"Lật mảnh ghép",grid:S.grid,time:S.time,answerMode:S.answerMode,qs:S.qs.slice(0,S.grid*S.grid),img};let link=location.origin+location.pathname+"#play="+toBase64(data);$("#shareLink").value=link;$("#shareBox").classList.remove("hidden");if(link.length>1800000)$("#shareBox small").textContent="⚠ Link khá dài. Vẫn có thể gửi bằng Zalo/Messenger, nhưng không nên tạo QR từ link này.";else $("#shareBox small").textContent="Học sinh mở link này trên điện thoại/iPad/máy tính và tự làm bài. Không cần đăng nhập.";navigator.clipboard?.writeText(link).catch(()=>{});}finally{$("#shareBtn").disabled=false;$("#shareBtn").textContent="🔗 Giao bài cho học sinh"}}
function copyShare(){let v=$("#shareLink").value;navigator.clipboard?.writeText(v).then(()=>$("#copyShareBtn").textContent="✓ Đã sao chép").catch(()=>{ $("#shareLink").select();document.execCommand("copy");$("#copyShareBtn").textContent="✓ Đã sao chép"});setTimeout(()=>$("#copyShareBtn").textContent="Sao chép",1800)}

function loadStudentLink(){if(!location.hash.startsWith("#play="))return;try{let d=fromBase64(location.hash.slice(6));S.payload=d;S.grid=d.grid;S.time=d.time;S.answerMode=d.answerMode||"hide";S.qs=d.qs;S.img=d.img;$("#setup").classList.add("hidden");$("#student").classList.remove("hidden");$("#studentTitle").textContent=d.title||"Lật mảnh ghép";$("#studentMeta").textContent=d.grid+"×"+d.grid+" • "+d.qs.length+" câu • "+Math.round(d.time/60)+" phút";}catch(e){alert("Link giao bài không hợp lệ hoặc đã bị cắt.");}}
check();loadStudentLink();